name: CargoApiK8JobDeploy

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted  

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Check Node.js Version
      run: node -v 

    - name: Install Dependencies
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
      working-directory: k8-comm 

    - name: Build TypeScript Files
      run: npm run build
      working-directory: k8-comm 

    - name: Restart Application with PM2
      run: |
        sudo pm2 describe cargoapi > /dev/null
        if [ $? -ne 0 ]; then
          sudo pm2 start dist/server.js --name "cargoapi"
        else
          sudo pm2 restart "cargoapi"
        fi
      working-directory: k8-comm 

    - name: Restart Nginx
      run: sudo systemctl restart nginx
