name: CargoApiK8JobDeploy

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted  

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Use System Node.js (Skip setup-node)
      run: node -v 

    - name: Ensure Deployment Directory Exists
      run: |
        if [ ! -d "/var/www/cargodeployapi.slacky.xyz" ]; then
          sudo mkdir -p /var/www/cargodeployapi.slacky.xyz
          sudo chown -R $USER:$USER /var/www/cargodeployapi.slacky.xyz
        fi

    - name: Sync Repository to Deployment Directory
      run: rsync -av --delete ./ /var/www/cargodeployapi.slacky.xyz/CargoDeploy
    
    - name: Install Dependencies
      run: npm ci
      working-directory: /var/www/cargodeployapi.slacky.xyz/CargoDeploy/k8-comm 

    - name: Build TypeScript Files
      run: npm run build
      working-directory: /var/www/cargodeployapi.slacky.xyz/CargoDeploy/k8-comm 

    - name: Restart Application with PM2
      run: |
        cd /var/www/cargodeployapi.slacky.xyz/CargoDeploy/k8-comm
        sudo pm2 describe cargoapi > /dev/null
        if [ $? -ne 0 ]; then
          sudo pm2 start dist/server.js --name "cargoapi"
        else
          sudo pm2 restart "cargoapi"
        fi

    - name: Reload Nginx
      run: sudo systemctl reload nginx
